version: 2.1

aliases:
  working_directory: &working_directory
    working_directory: ~/factory_trace

executors:
  default:
    description: The official CircleCI Ruby Docker image
    parameters:
      tag:
        description: The circleci/ruby Docker image version tag
        type: string
        default: latest
    docker:
      - image: circleci/ruby:<< parameters.tag >>
    environment:
      - BUNDLE_JOBS: 4
      - BUNDLE_RETRY: 3
    <<: *working_directory

jobs:
  checkout:
    executor: default
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/factory_trace
          paths:
            - .

  rspec:
    parameters:
      ruby-version:
        type: string
      fb-version:
        type: string
    executor:
      name: default
      tag: << parameters.ruby-version >>
    docker:
      - image: circleci/ruby:<< parameters.ruby-version >>
    steps:
      - attach_workspace:
          at: ~/factory_trace
      - run: |
          FB_VERSION=<< parameters.fb-version >> bundle install
      - run: |
          FB_VERSION=<< parameters.fb-version >> ruby spec/factory_trace/integration_tests/runner.rb
      - run: |
          FB_VERSION=<< parameters.fb-version >> bundle exec rspec --profile 10 \
                                                                   --format RspecJunitFormatter \
                                                                   --out test_results/rspec.xml \
                                                                   --format progress \
                                                                   $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
          path: test_results

workflows:
  version: 2
  default: &default
    jobs:
      - checkout
      - rspec:
          requires:
            - checkout
          matrix:
            parameters:
              ruby-version: [
                "2.5",
                "2.6",
                "2.7",
                "3.0",
                "latest"
              ]
              fb-version: [
                "4.10",
                "4.11",
                "5.0",
                "5.1",
                "5.2",
                "6.0"
                # "6.1",
                # "6.2"
              ]
            exclude:
              - ruby-version: "3.0"
                fb-version: "4.10"
              - ruby-version: "3.0"
                fb-version: "4.11"
              - ruby-version: "3.0"
                fb-version: "5.0"
              - ruby-version: "3.0"
                fb-version: "5.1"
              - ruby-version: "3.0"
                fb-version: "5.2"
              - ruby-version: "3.0"
                fb-version: "6.0"
              - ruby-version: "latest"
                fb-version: "4.10"
              - ruby-version: "latest"
                fb-version: "4.11"
              - ruby-version: "latest"
                fb-version: "5.0"
              - ruby-version: "latest"
                fb-version: "5.1"
              - ruby-version: "latest"
                fb-version: "5.2"
              - ruby-version: "latest"
                fb-version: "6.0"
          name: rspec-ruby-<< matrix.ruby-version >>/fb-<< matrix.fb-version >>

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    <<: *default
